set -g default-terminal "screen-256color"

unbind %
bind | split-window -h #bind to split horizontally the pane

unbind '"'
bind - split-window -v #bind to split vertically the pane

unbind r
bind r source-file ~/.tmux.conf #bind to reload tmuxkconfig

set-window-option -g mode-keys vi

bind j resize-pane -D 5 #bind j to size pane down
bind k resize-pane -U 5 #bind k to size pane up
bind l resize-pane -R 5 #bind l to size pane to the right
bind h resize-pane -L 5 #bind h to size pane to the left

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse
set -g mouse on #activate mouse on tmux

# ...alongside
set -g @plugin 'tmux-plugins/tpm'   
#tpm plugin

#list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# initialize TMUX plugin manager (SHOULD ALWAYS BE AT THE BOTTOM)
run '~/.tmux/plugins/tpm/tpm'
